=== Logiqx/logiqx-www/Dats/DTD/dats.dtd
<!ELEMENT contents_page (section+)>
<!ELEMENT section (img, type, comment, emulators?)>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img src CDATA "" width CDATA "" height CDATA "">
<!ELEMENT type (#PCDATA)>
<!ELEMENT emulators (emulator+)>

<!ELEMENT emulator_page (emulator+)>
<!ELEMENT emulator (img, name, version, suitability, status, date, games, author?, comment?, dats, revisions)>
<!ATTLIST emulator id NMTOKEN #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT suitability (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT games (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author href CDATA "">
<!ELEMENT comment (#PCDATA | p | ul| b | br | a )*>
<!ELEMENT p (#PCDATA | br | a | u)*>
<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA | p | a | b | br)*>
<!ELEMENT br (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA "">

<!ELEMENT dats (dat+)>
<!ELEMENT dat (dat_type, file)>
<!ELEMENT dat_type (#PCDATA)>
<!ATTLIST dat_type path CDATA "">
<!ELEMENT file (#PCDATA)>
<!ATTLIST file name CDATA "" size NMTOKEN #REQUIRED>

<!ELEMENT revisions (revision+)>
<!ELEMENT revision (date, comment)>

<!ENTITY CMPro "<dat_type path='CMP_Dats'>CMPro</dat_type>">
<!ENTITY ROMCenter "<dat_type path='RC_Dats'>ROMCenter</dat_type>">

=== Logiqx/logiqx-www/Dats/Dats.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by nobody (nowhere) -->
<!DOCTYPE contents_page SYSTEM "dtd/dats.dtd" [
	<!ENTITY Daphne SYSTEM "Daphne/Daphne.ent.xml">
	<!ENTITY FinalBurnAlpha SYSTEM "FinalBurnAlpha/FinalBurnAlpha.ent.xml">
	<!ENTITY MAMEBeta SYSTEM "MAMEBeta/MAMEBeta.ent.xml">
	<!ENTITY MAMEChanges SYSTEM "MAMEChanges/MAMEChanges.ent.xml">
	<!ENTITY Nebula SYSTEM "Nebula/Nebula.ent.xml">
	<!ENTITY NebulaModel2 SYSTEM "NebulaModel2/NebulaModel2.ent.xml">
	<!ENTITY RAINE SYSTEM "RAINE/RAINE.ent.xml">
	<!ENTITY Tickle SYSTEM "Tickle/Tickle.ent.xml">
	<!ENTITY WinKawaks SYSTEM "WinKawaks/WinKawaks.ent.xml">
	<!ENTITY OlderEmus SYSTEM "OlderEmus/OlderEmus.ent.xml">
	<!ENTITY CPS1 SYSTEM "CPS-1/CPS-1.ent.xml">
	<!ENTITY CPS2 SYSTEM "CPS-2/CPS-2.ent.xml">
	<!ENTITY NeoGeo SYSTEM "Neo-Geo/Neo-Geo.ent.xml">
	<!ENTITY ZN SYSTEM "ZN/ZN.ent.xml">
	<!ENTITY M1 SYSTEM "M1/M1.ent.xml">
	<!ENTITY NebulaJukebox SYSTEM "NebulaJukebox/NebulaJukebox.ent.xml">
	<!ENTITY NeoJukeBox SYSTEM "NeoJukeBox/NeoJukeBox.ent.xml">
	<!ENTITY QPlayer SYSTEM "QPlayer/QPlayer.ent.xml">
	<!ENTITY MAMEArtwork SYSTEM "MAMEArtwork/MAMEArtwork.ent.xml">
	<!ENTITY MAMESamples SYSTEM "MAMESamples/MAMESamples.ent.xml">
]>
<contents_page>
	<section>
		<img src="RecentEmus.gif" width="158" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Emulators that are up to six months old or likely to receive further updates.</p>
		</comment>
		<emulators>
			&Daphne;
			&FinalBurnAlpha;
			&MAMEBeta;
			&MAMEChanges;
			&Nebula;
			&NebulaModel2;
			&RAINE;
			&Tickle;
			&WinKawaks;
		</emulators>
	</section>
	<section>
		<img src="OlderEmus.gif" width="140" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Emulators that are more than six months old.</p>
		</comment>
		<emulators>
			&OlderEmus;
		</emulators>
	</section>
	<section>
		<img src="Systems.gif" width="104" height="40"/>
		<type>System</type>
		<comment>
			<p>General systems used by multiple emulators.</p>
		</comment>
		<emulators>
			&CPS1;
			&CPS2;
			&NeoGeo;
			&ZN;
		</emulators>
	</section>
	<section>
		<img src="SoundEmus.gif" width="151" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Emulators that can play sound from the games but not the games themselves.</p>
		</comment>
		<emulators>
			&M1;
			&NebulaJukebox;
			&NeoJukeBox;
			&QPlayer;
		</emulators>
	</section>
	<section>
		<img src="ResourceFiles.gif" width="177" height="40"/>
		<type>Resource</type>
		<comment>
			<p>Additional resources that enhance the emulation of games.</p>
		</comment>
		<emulators>
			&MAMEArtwork;
			&MAMESamples;
		</emulators>
	</section>
</contents_page>

=== Logiqx/logiqx-www/Dats/RomCenter.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by nobody (nowhere) -->
<!DOCTYPE contents_page SYSTEM "dtd/dats.dtd" [
	<!ENTITY CottAGE SYSTEM "CottAGE/CottAGE.ent.xml">
	<!ENTITY Daphne SYSTEM "Daphne/Daphne.ent.xml">
	<!ENTITY FinalBurnAlpha SYSTEM "FinalBurnAlpha/FinalBurnAlpha.ent.xml">
	<!ENTITY FinalBurn SYSTEM "FinalBurn/FinalBurn.ent.xml">
	<!ENTITY MAMEBeta SYSTEM "MAMEBeta/MAMEBeta.ent.xml">
	<!ENTITY MAMEChanges SYSTEM "MAMEChanges/MAMEChanges.ent.xml">
	<!ENTITY MAMETestDrivers SYSTEM "MAMETestDrivers/MAMETestDrivers.ent.xml">
	<!ENTITY RAINE SYSTEM "RAINE/RAINE.ent.xml">
	<!ENTITY OlderEmus SYSTEM "OlderEmus/OlderEmus.ent.xml">
	<!ENTITY CPS2 SYSTEM "CPS-2/CPS-2.ent.xml">
	<!ENTITY CPS1 SYSTEM "CPS-1/CPS-1.ent.xml">
	<!ENTITY ZN SYSTEM "ZN/ZN.ent.xml">
	<!ENTITY NeoGeo SYSTEM "Neo-Geo/Neo-Geo.ent.xml">
	<!ENTITY QPlayer SYSTEM "QPlayer/QPlayer.ent.xml">
	<!ENTITY NeoJukeBox SYSTEM "NeoJukeBox/NeoJukeBox.ent.xml">
	<!ENTITY NebulaJukebox SYSTEM "NebulaJukebox/NebulaJukebox.ent.xml">
	<!ENTITY Nebula SYSTEM "Nebula/Nebula.ent.xml">
	<!ENTITY NebulaModel2 SYSTEM "NebulaModel2/NebulaModel2.ent.xml">
	<!ENTITY MAMEArtwork SYSTEM "MAMEArtwork/MAMEArtwork.ent.xml">
	<!ENTITY MAMECabinets SYSTEM "MAMECabinets/MAMECabinets.ent.xml">
	<!ENTITY MAMEFlyers SYSTEM "MAMEFlyers/MAMEFlyers.ent.xml">
	<!ENTITY MAMEIcons SYSTEM "MAMEIcons/MAMEIcons.ent.xml">
	<!ENTITY MAMEMarquees SYSTEM "MAMEMarquees/MAMEMarquees.ent.xml">
	<!ENTITY MAMEPanels SYSTEM "MAMEPanels/MAMEPanels.ent.xml">
	<!ENTITY MAMESamples SYSTEM "MAMESamples/MAMESamples.ent.xml">
	<!ENTITY MAMESnaps SYSTEM "MAMESnaps/MAMESnaps.ent.xml">
	<!ENTITY MAMETitles SYSTEM "MAMETitles/MAMETitles.ent.xml">
	<!ENTITY MAMusIcons SYSTEM "MAMusIcons/MAMusIcons.ent.xml">
	<!ENTITY CrashTestsMAMEScreenshots SYSTEM "CrashTestsMAMEScreenshots/CrashTestsMAMEScreenshots.ent.xml">
	<!ENTITY M1 SYSTEM "M1/M1.ent.xml">
	<!ENTITY WinKawaks SYSTEM "WinKawaks/WinKawaks.ent.xml">
	<!ENTITY Zinc SYSTEM "Zinc/Zinc.ent.xml">
	<!ENTITY MPU SYSTEM "MPU/MPU.ent.xml">
	<!ENTITY VivaNonno SYSTEM "VivaNonno/VivaNonno.ent.xml">
]>
<contents_page>
	<section>
		<img src="RecentEmus.gif" width="158" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Emulators that are up to six months old or likely to receive further updates.</p>
		</comment>
		<emulators>
&CottAGE;
&Daphne;
&FinalBurnAlpha;
&FinalBurn;
&MAMEBeta;
&MAMEChanges;
&MAMETestDrivers;
&Nebula;
&NebulaModel2;
&RAINE;
&VivaNonno;
&WinKawaks;
		</emulators>
	</section>
	<section>
		<img src="OlderEmus.gif" width="140" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Emulators that are more than six months old</p>
		</comment>
		<emulators>
&OlderEmus;
		</emulators>
	</section>
	<section>
		<img src="Systems.gif" width="104" height="40"/>
		<type>System</type>
		<comment>
			<p>General Systems</p>
		</comment>
		<emulators>
&CPS1;
&CPS2;
&NeoGeo;
&ZN;
		</emulators>
	</section>
	<section>
		<img src="Systems.gif" width="104" height="40"/>
		<type>System</type>
		<comment>
			<p>Slightly Arcade Related (Fruit Machines/Pinball)</p>
		</comment>
		<emulators>
&MPU;
		</emulators>
	</section>
	<section>
		<img src="SoundEmus.gif" width="151" height="40"/>
		<type>Emulator</type>
		<comment>
			<p>Sound Emulators</p>
		</comment>
		<emulators>
&Hoot;
&M1;
&NebulaJukebox;
&NeoJukeBox;
&QPlayer;
		</emulators>
	</section>
	<section>
		<img src="ResourceFiles.gif" width="177" height="40"/>
		<type>Resource</type>
		<comment>
			<p>Resource Files</p>
		</comment>
		<emulators>
&CrashTestsMAMEScreenshots;		
&MAMEArtwork;
&MAMECabinets;
&MAMEFlyers;
&MAMEIcons;
&MAMEMarquees;
&MAMEPanels;
&MAMESamples;
&MAMESnaps;
&MAMETitles;
&MAMusIcons;
		</emulators>
	</section>
</contents_page>
